item_group = {
'AC': 'AUD',
'AM': 'AUD',
'AS': 'AUD',
'AU': 'AUD',
'BE': 'PB',
'BG': 'HC',
'C': 'HC',
'D':  'EB',
'DV': 'MSC',
'E': 'EB',
'EA': 'EB',
'EK': 'EB',
'ES': 'EB',
'F': 'EB',
'G': 'EB',
'J': 'JRN',
'M': 'PB',
'O': 'HC',
'P': 'PB',
'V': 'MSC',
'VH': 'MSC'
}
product_type_map = {
'AC': ['AUD', 'AUDIO'],
'AM': ['AUD', 'AUDIO'],
'AS': ['AUD', 'E-AUD'],
'AU': ['AUD', 'AUDIO'],
'BE': ['PB', 'SPRL'],
'BG': ['HC', 'LTHR'],
'C': ['HC', 'CLOTH'],
'D': ['EB', 'DISK'],
'DV': ['MSC', 'DVD'],
'E': ['EB', 'DIGTL'],
'EA': ['EB', 'PDF'],
'EK': ['EB', 'DIGTL'],
'ES': ['EB', 'EISU'],
'F': ['EB', 'EPUB'],
'G': ['EB', 'DIGTL'],
'J': ['JRN', 'JRNL'],
'M': ['PB', 'MASS'],
'O': ['HC', 'OTHER'],
'P': ['PB', 'PAPER'],
'V': ['MSC', 'VIDEO'],
'VH': ['MSC', 'VIDEO']
}
i1cat_to_i1pkg_map = {
'AUD': 'AUDIO',
'AUD': 'AUDIO',
'AUD': 'E-AUD',
'AUD': 'AUDIO',
'PB': 'SPRL',
'HC': 'LTHR',
'HC': 'CLOTH',
'EB': 'DISK',
'MSC': 'DVD',
'EB': 'DIGTL',
'EB': 'PDF',
'EB': 'DIGTL',
'EB': 'EISU',
'EB': 'EPUB',
'EB': 'DIGTL',
'JRN': 'JRNL',
'PB': 'MASS',
'HC': 'OTHER',
'PB': 'PAPER',
'MSC': 'VIDEO',
'MSC': 'VIDEO'
}