field_map = {
'I1CLS': 'Company NO',
'I1GRP': 'I1GRP',
'I1PKG': 'I1GRP',
'I1CAT': 'Minor Disc ID',
'I1I': 'I1I',
'I1AI': 'I1AI',
'I1SUPI': 'I1SUPI',
'I1IDSC': 'I1IDSC',
'I1IDIS': 'Discount ID',
'I1IEDC': 'I1IEDC',
'I1CMNT': 'I1CMNT',
'I1ORGN': 'Country Of Origin',
'I1PACK': 'Set Code',
'I1STKF': 'Non Stock Flag',
'I1WGHN': 'Weight Oz',
'I1STKR': 'I1STKR',
'I1ISTS': 'I1STKR',
'I1FRCHG': 'Non Stock Flag',
'I1CRTQ': 'Case Qty',
'I1REGD': 'Entered Date',
'I1REGU': 'Entered User ID',
'I1CHGZ': 'Last Change Date',
'I1CHGU': 'Last Change User ID'
}