DLCD00P_Field_format = [
'C4CN','A','10',
'C4DLVN','N','3',
'C4DCNM','A','60',
'C4DAD0','A','60',
'C4DAD1','A','60',
'C4DAD2','A','60',
'C4DAD3','A','60',
'C4DAD4','A','20',
'C4DAD5','A','20',
'C4DAD6','A','60',
'C4DPHN','A','20',
'C4DFAX','A','20',
'C4DXNO','A','10',
'C4DXLOC','A','20',
'C4CSTS','A','1',
'C4SRCH','A','10',
'C4CAR','A','2',
'C4FAGC','A','2',
'C4DSTP','A','3',
'C4RUN','A','3'
]

DLCD00P_Book_customer_addresses = [
'Customer ID','A','20',
'Address ID','A','20',
'Address Type','A','20',
'Full.Name','A','20',
'Address Description','A','20',
'Address Line 1','A','20',
'Address Line 2','A','20',
'Address Line 3','A','20',
'City','A','20',
'State','A','20',
'Zip Code','A','20',
'Address Country Id','A','20',
'Telephone Area','A','20',
'Telephone Number','A','20',
'Fax Area','A','20',
'Fax Number','A','20',
'Do Not Use Indicator','A','20',
'Attention','A','20',
'Name Name Class Id','A','20',
'Last Purchase Date','A','20',
'Last Changed Date','A','20',
'Last Changed Time','A','20',
'Last Changed By User Id','A','20',
'Create Date','A','20',
'Created By User Id','A','20',
'Customer Tax Exempt Id','A','20',
'Tax Region','A','20',
'Tax Code Value','A','20',
'SAN Number','A','20',
'Ship Method IDs','A','20',
'Ship Method Shipper IDs','A','20',
'Shipper ID','A','20',
'Returnable Ind','A','20',
'Active IND','A','20',
'Address No','A','20',
'Backorder Minimum Qty','A','20',
'Bill To SAN Number','A','20',
'Contact','A','20',
'Contact Title','A','20',
'Cust Class ID','A','20',
'Customer Addr ID','A','20',
'Default Warehouse ID','A','20',
'Discnt Cust Class','A','20',
'Discnt Returnable IND','A','20',
'EDI Allow Backorders IND','A','20',
'Edi Order Type','A','20',
'EDI Partner Code','A','20',
'Pallet Capable IND','A','20',
'Picklist Minimum Qty','A','20',
'Sales Rep ID','A','20',
'User Field Names','A','20'
]
