field_map = {
'D1SEQDM': 'NAME.ID or Recipient ID',
'D1SAL': 'CONTACT.SALUTATION',
'D1FMNM': 'LAST.NAME',
'D1MDNM': 'MIDDLE.NAME',
'D1GVNM': 'FIRST.NAME',
'D1NMSFX': 'SUFFIX',
'D1FNM': 'FULL.NAME',
'D1COMP': 'EMPLOYER.NAME.ID',
'D1DPNM': 'SPECIFIC.JOB.TITLE',
'D1POSN': 'JOB.TITLE.ID',
'D1CRTZ': 'CREATE.DATE',
'D1CRTU': 'CREATED.BY.USER.ID',
'D4ADRFMT': 'ADDRESS.TYPE',
'D4ADRL0': 'Map from Address ID',
'D4STS': 'DO.NOT.USE.IND',
'CECN': 'NAME.ID or RECIPIENT.ID',
'CECT': 'CONTACT.TYPE'
}

D4ADRDSC_map = {
'BUS': 'BUSINESS',
'HOM': 'HOME',
'AR': 'ACCOUNTS RECEIVABLE',
'ORD': 'ORDER DEPARTMENT',
'DAY': 'DAYTIME'
}

D1POSN_map = {
'AP': 'Accounts Payable',
'OW': 'Owner',
'PR':'Buyer/Purchasing',
'SM': 'Store Manager',
'SR': 'Sales Representative'
}